services:
  postgres:
      image: postgres:latest
      restart: unless-stopped
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=email-send
      ports:
        - "5432:5432"
      volumes:
        - pg:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" 
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: "testuser"
      MINIO_ROOT_PASSWORD: "testpassword"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
volumes:
  pg:
  minio_data:
